name = "FAMOS"
uuid = "5b717abc-8e53-44a9-b2f5-38223789851d"
authors = ["Qiwen Huang", "Marius Weidmann"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
